# Exploration des CSV bruts

## 1. Chargement

In [1]:
# Recharge auto du package `datalake` à chaque exécution (dev sans redémarrage)
%load_ext autoreload
%autoreload 2

import polars as pl
from datalake import explore

pl.Config.set_tbl_cols(50)         # afficher toutes les colonnes
pl.Config.set_fmt_str_lengths(80)  # ne pas tronquer les chaînes longues
paths = explore.csv_paths()
[p.name for p in paths]

['LineA_Stable_10K.csv',
 'LineB_Flux.csv',
 'LineC_Turbulent.csv',
 'LineD_SpikeControl.csv',
 'LineE_SmoothRun.csv']

## 1 bis. Aperçu — 5 premières lignes de chaque fichier

Pour visualiser concrètement le contenu : valeurs, format du `timestamp`, et la
casse réelle des colonnes telle qu'elle apparaît dans chaque fichier.

In [2]:
from IPython.display import display, Markdown

for p in paths:
    display(Markdown(f"**{p.name}** — aperçu (5 lignes)"))
    display(explore.head(p))
    display(Markdown("_Statistiques descriptives_"))
    display(explore.describe(p))

**LineA_Stable_10K.csv** — aperçu (5 lignes)

shape: (5, 5)
┌─────────────────────┬─────────────┬────────────┬──────────────┬───────┐
│ timestamp           ┆ Temperature ┆ pressure   ┆ elapsed_time ┆ label │
│ ---                 ┆ ---         ┆ ---        ┆ ---          ┆ ---   │
│ str                 ┆ f64         ┆ f64        ┆ f64          ┆ i64   │
╞═════════════════════╪═════════════╪════════════╪══════════════╪═══════╡
│ 2025-05-01 00:00:00 ┆ 180.064573  ┆ 159.905011 ┆ 35.069657    ┆ 0     │
│ 2025-05-01 00:01:00 ┆ 179.982026  ┆ 159.95723  ┆ 35.056665    ┆ 0     │
│ 2025-05-01 00:02:00 ┆ 180.0842    ┆ 159.916367 ┆ 34.812696    ┆ 0     │
│ 2025-05-01 00:03:00 ┆ 180.197994  ┆ 160.015459 ┆ 35.115917    ┆ 0     │
│ 2025-05-01 00:04:00 ┆ 179.96956   ┆ 160.167605 ┆ 34.701983    ┆ 0     │
└─────────────────────┴─────────────┴────────────┴──────────────┴───────┘

_Statistiques descriptives_

shape: (9, 6)
┌────────────┬─────────────────────┬─────────────┬────────────┬──────────────┬─────────┐
│ statistic  ┆ timestamp           ┆ Temperature ┆ pressure   ┆ elapsed_time ┆ label   │
│ ---        ┆ ---                 ┆ ---         ┆ ---        ┆ ---          ┆ ---     │
│ str        ┆ str                 ┆ f64         ┆ f64        ┆ f64          ┆ f64     │
╞════════════╪═════════════════════╪═════════════╪════════════╪══════════════╪═════════╡
│ count      ┆ 10000               ┆ 10000.0     ┆ 10000.0    ┆ 10000.0      ┆ 10000.0 │
│ null_count ┆ 0                   ┆ 0.0         ┆ 0.0        ┆ 0.0          ┆ 0.0     │
│ mean       ┆ null                ┆ 180.008722  ┆ 159.996495 ┆ 35.001107    ┆ 0.0018  │
│ std        ┆ null                ┆ 0.248329    ┆ 0.187283   ┆ 0.216139     ┆ 0.04239 │
│ min        ┆ 2025-05-01 00:00:00 ┆ 179.490088  ┆ 156.797644 ┆ 34.268983    ┆ 0.0     │
│ 25%        ┆ null                ┆ 179.912689  ┆ 159.906894 ┆ 34.860043    ┆ 0.0     │
│ 50%        ┆ null                ┆ 180.000098  ┆ 160.001911 ┆ 34.999392    ┆ 0.0     │
│ 75%        ┆ null                ┆ 180.088009  ┆ 160.096698 ┆ 35.133728    ┆ 0.0     │
│ max        ┆ 2025-05-07 22:39:00 ┆ 185.186624  ┆ 160.627072 ┆ 37.232384    ┆ 1.0     │
└────────────┴─────────────────────┴─────────────┴────────────┴──────────────┴─────────┘

**LineB_Flux.csv** — aperçu (5 lignes)

shape: (5, 5)
┌─────────────────────┬─────────────┬────────────┬──────────────┬───────┐
│ timestamp           ┆ temperature ┆ pressure   ┆ Elapsed_time ┆ label │
│ ---                 ┆ ---         ┆ ---        ┆ ---          ┆ ---   │
│ str                 ┆ f64         ┆ f64        ┆ f64          ┆ i64   │
╞═════════════════════╪═════════════╪════════════╪══════════════╪═══════╡
│ 2025-04-01 00:00:00 ┆ 190.496714  ┆ 119.57624  ┆ 19.728602    ┆ 0     │
│ 2025-04-01 00:01:00 ┆ 189.861736  ┆ 119.546586 ┆ 19.8778      ┆ 0     │
│ 2025-04-01 00:02:00 ┆ 190.647689  ┆ 118.204357 ┆ 19.761048    ┆ 0     │
│ 2025-04-01 00:03:00 ┆ 191.52303   ┆ 119.66991  ┆ 20.044167    ┆ 0     │
│ 2025-04-01 00:04:00 ┆ 189.765847  ┆ 120.732829 ┆ 20.478871    ┆ 0     │
└─────────────────────┴─────────────┴────────────┴──────────────┴───────┘

_Statistiques descriptives_

shape: (9, 6)
┌────────────┬─────────────────────┬─────────────┬────────────┬──────────────┬──────────┐
│ statistic  ┆ timestamp           ┆ temperature ┆ pressure   ┆ Elapsed_time ┆ label    │
│ ---        ┆ ---                 ┆ ---         ┆ ---        ┆ ---          ┆ ---      │
│ str        ┆ str                 ┆ f64         ┆ f64        ┆ f64          ┆ f64      │
╞════════════╪═════════════════════╪═════════════╪════════════╪══════════════╪══════════╡
│ count      ┆ 5000                ┆ 5000.0      ┆ 5000.0     ┆ 5000.0       ┆ 5000.0   │
│ null_count ┆ 0                   ┆ 0.0         ┆ 0.0        ┆ 0.0          ┆ 0.0      │
│ mean       ┆ null                ┆ 190.115602  ┆ 119.900126 ┆ 20.024221    ┆ 0.01     │
│ std        ┆ null                ┆ 1.490169    ┆ 1.353817   ┆ 0.451237     ┆ 0.099509 │
│ min        ┆ 2025-04-01 00:00:00 ┆ 186.758733  ┆ 108.946513 ┆ 18.649768    ┆ 0.0      │
│ 25%        ┆ null                ┆ 189.347911  ┆ 119.281935 ┆ 19.736817    ┆ 0.0      │
│ 50%        ┆ null                ┆ 190.021312  ┆ 119.972616 ┆ 20.006972    ┆ 0.0      │
│ 75%        ┆ null                ┆ 190.682069  ┆ 120.667548 ┆ 20.280089    ┆ 0.0      │
│ max        ┆ 2025-04-04 11:19:00 ┆ 202.719378  ┆ 123.529055 ┆ 22.978308    ┆ 1.0      │
└────────────┴─────────────────────┴─────────────┴────────────┴──────────────┴──────────┘

**LineC_Turbulent.csv** — aperçu (5 lignes)

shape: (5, 4)
┌─────────────────────┬─────────────┬────────────┬───────┐
│ timestamp           ┆ Temperature ┆ pressure   ┆ label │
│ ---                 ┆ ---         ┆ ---        ┆ ---   │
│ str                 ┆ f64         ┆ f64        ┆ i64   │
╞═════════════════════╪═════════════╪════════════╪═══════╡
│ 2025-03-01 00:00:00 ┆ 200.819578  ┆ 99.432162  ┆ 0     │
│ 2025-03-01 00:01:00 ┆ 199.771864  ┆ 99.392425  ┆ 0     │
│ 2025-03-01 00:02:00 ┆ 201.068686  ┆ 97.593838  ┆ 0     │
│ 2025-03-01 00:03:00 ┆ 202.512999  ┆ 99.557679  ┆ 0     │
│ 2025-03-01 00:04:00 ┆ 199.613647  ┆ 100.981991 ┆ 0     │
└─────────────────────┴─────────────┴────────────┴───────┘

_Statistiques descriptives_

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────┬────────────┬──────────┐
│ statistic  ┆ timestamp           ┆ Temperature ┆ pressure   ┆ label    │
│ ---        ┆ ---                 ┆ ---         ┆ ---        ┆ ---      │
│ str        ┆ str                 ┆ f64         ┆ f64        ┆ f64      │
╞════════════╪═════════════════════╪═════════════╪════════════╪══════════╡
│ count      ┆ 5000                ┆ 5000.0      ┆ 5000.0     ┆ 5000.0   │
│ null_count ┆ 0                   ┆ 0.0         ┆ 0.0        ┆ 0.0      │
│ mean       ┆ null                ┆ 200.449243  ┆ 99.626769  ┆ 0.04     │
│ std        ┆ null                ┆ 2.71024     ┆ 2.219519   ┆ 0.195979 │
│ min        ┆ 2025-03-01 00:00:00 ┆ 194.651909  ┆ 88.317668  ┆ 0.0      │
│ 25%        ┆ null                ┆ 198.967822  ┆ 98.926012  ┆ 0.0      │
│ 50%        ┆ null                ┆ 200.113129  ┆ 99.921164  ┆ 0.0      │
│ 75%        ┆ null                ┆ 201.254092  ┆ 100.865493 ┆ 0.0      │
│ max        ┆ 2025-03-04 11:19:00 ┆ 216.268627  ┆ 104.728934 ┆ 1.0      │
└────────────┴─────────────────────┴─────────────┴────────────┴──────────┘

**LineD_SpikeControl.csv** — aperçu (5 lignes)

shape: (5, 4)
┌─────────────────────┬─────────────┬────────────┬───────┐
│ timestamp           ┆ temperature ┆ Pressure   ┆ label │
│ ---                 ┆ ---         ┆ ---        ┆ ---   │
│ str                 ┆ f64         ┆ f64        ┆ i64   │
╞═════════════════════╪═════════════╪════════════╪═══════╡
│ 2025-02-01 00:00:00 ┆ 200.794743  ┆ 99.491488  ┆ 0     │
│ 2025-02-01 00:01:00 ┆ 199.778777  ┆ 99.455903  ┆ 0     │
│ 2025-02-01 00:02:00 ┆ 201.036302  ┆ 97.845228  ┆ 0     │
│ 2025-02-01 00:03:00 ┆ 202.436848  ┆ 99.603892  ┆ 0     │
│ 2025-02-01 00:04:00 ┆ 199.625355  ┆ 100.879395 ┆ 0     │
└─────────────────────┴─────────────┴────────────┴───────┘

_Statistiques descriptives_

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────┬────────────┬──────────┐
│ statistic  ┆ timestamp           ┆ temperature ┆ Pressure   ┆ label    │
│ ---        ┆ ---                 ┆ ---         ┆ ---        ┆ ---      │
│ str        ┆ str                 ┆ f64         ┆ f64        ┆ f64      │
╞════════════╪═════════════════════╪═════════════╪════════════╪══════════╡
│ count      ┆ 5000                ┆ 5000.0      ┆ 5000.0     ┆ 5000.0   │
│ null_count ┆ 0                   ┆ 0.0         ┆ 0.0        ┆ 0.0      │
│ mean       ┆ null                ┆ 200.032963  ┆ 99.961151  ┆ 0.003    │
│ std        ┆ null                ┆ 1.658553    ┆ 1.304181   ┆ 0.054696 │
│ min        ┆ 2025-02-01 00:00:00 ┆ 194.813972  ┆ 90.427748  ┆ 0.0      │
│ 25%        ┆ null                ┆ 198.953479  ┆ 99.157651  ┆ 0.0      │
│ 50%        ┆ null                ┆ 200.024989  ┆ 99.976098  ┆ 0.0      │
│ 75%        ┆ null                ┆ 201.073458  ┆ 100.810164 ┆ 0.0      │
│ max        ┆ 2025-02-04 11:19:00 ┆ 213.108972  ┆ 104.234866 ┆ 1.0      │
└────────────┴─────────────────────┴─────────────┴────────────┴──────────┘

**LineE_SmoothRun.csv** — aperçu (5 lignes)

shape: (5, 4)
┌─────────────────────┬─────────────┬────────────┬───────┐
│ timestamp           ┆ Temperature ┆ pressure   ┆ label │
│ ---                 ┆ ---         ┆ ---        ┆ ---   │
│ str                 ┆ f64         ┆ f64        ┆ i64   │
╞═════════════════════╪═════════════╪════════════╪═══════╡
│ 2025-01-01 00:00:00 ┆ 200.248357  ┆ 99.89406   ┆ 0     │
│ 2025-01-01 00:01:00 ┆ 199.930868  ┆ 99.886646  ┆ 0     │
│ 2025-01-01 00:02:00 ┆ 200.323844  ┆ 99.551089  ┆ 0     │
│ 2025-01-01 00:03:00 ┆ 200.761515  ┆ 99.917477  ┆ 0     │
│ 2025-01-01 00:04:00 ┆ 199.882923  ┆ 100.183207 ┆ 0     │
└─────────────────────┴─────────────┴────────────┴───────┘

_Statistiques descriptives_

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────┬────────────┬──────────┐
│ statistic  ┆ timestamp           ┆ Temperature ┆ pressure   ┆ label    │
│ ---        ┆ ---                 ┆ ---         ┆ ---        ┆ ---      │
│ str        ┆ str                 ┆ f64         ┆ f64        ┆ f64      │
╞════════════╪═════════════════════╪═════════════╪════════════╪══════════╡
│ count      ┆ 5000                ┆ 5000.0      ┆ 5000.0     ┆ 5000.0   │
│ null_count ┆ 0                   ┆ 0.0         ┆ 0.0        ┆ 0.0      │
│ mean       ┆ null                ┆ 200.042801  ┆ 99.982532  ┆ 0.005    │
│ std        ┆ null                ┆ 0.756282    ┆ 0.32732    ┆ 0.070541 │
│ min        ┆ 2025-01-01 00:00:00 ┆ 198.379366  ┆ 96.753034  ┆ 0.0      │
│ 25%        ┆ null                ┆ 199.673117  ┆ 99.823333  ┆ 0.0      │
│ 50%        ┆ null                ┆ 200.009209  ┆ 99.994536  ┆ 0.0      │
│ 75%        ┆ null                ┆ 200.338938  ┆ 100.168097 ┆ 0.0      │
│ max        ┆ 2025-01-04 11:19:00 ┆ 209.596554  ┆ 100.882264 ┆ 1.0      │
└────────────┴─────────────────────┴─────────────┴────────────┴──────────┘

## 2. Volumétrie

In [3]:
explore.volumetry(paths)

shape: (5, 6)
┌────────────────────────┬────────┬──────────┬───────────┬──────────────┬──────────────┐
│ fichier                ┆ lignes ┆ colonnes ┆ taille_Ko ┆ nb_manquants ┆ elapsed_time │
│ ---                    ┆ ---    ┆ ---      ┆ ---       ┆ ---          ┆ ---          │
│ str                    ┆ i64    ┆ i64      ┆ i64       ┆ i64          ┆ bool         │
╞════════════════════════╪════════╪══════════╪═══════════╪══════════════╪══════════════╡
│ LineA_Stable_10K.csv   ┆ 10000  ┆ 5        ┆ 758       ┆ 0            ┆ true         │
│ LineB_Flux.csv         ┆ 5000   ┆ 5        ┆ 382       ┆ 0            ┆ true         │
│ LineC_Turbulent.csv    ┆ 5000   ┆ 4        ┆ 288       ┆ 0            ┆ false        │
│ LineD_SpikeControl.csv ┆ 5000   ┆ 4        ┆ 288       ┆ 0            ┆ false        │
│ LineE_SmoothRun.csv    ┆ 5000   ┆ 4        ┆ 288       ┆ 0            ┆ false        │
└────────────────────────┴────────┴──────────┴───────────┴──────────────┴──────────────┘

### Observations

- **LineA** : 10 000 enregistrements, soit **2× les autres** (5 000) → justifie le
  traitement **par chunks** demandé (simulation d'un flux).
- Nombre de colonnes : **5** pour LineA/LineB, **4** pour LineC/D/E (cf. `elapsed_time`).
- **0 valeur manquante** sur l'ensemble des fichiers.

## 3. Comparaison des schémas (casse des colonnes)

In [4]:
explore.casing_report(paths)

shape: (5, 4)
┌──────────────────────┬────────────────────────────┬──────────────┬──────────────────────────┐
│ colonne (normalisée) ┆ variantes                  ┆ nb_variantes ┆ présente_dans_n_fichiers │
│ ---                  ┆ ---                        ┆ ---          ┆ ---                      │
│ str                  ┆ str                        ┆ i64          ┆ i64                      │
╞══════════════════════╪════════════════════════════╪══════════════╪══════════════════════════╡
│ elapsed_time         ┆ Elapsed_time, elapsed_time ┆ 2            ┆ 2                        │
│ label                ┆ label                      ┆ 1            ┆ 5                        │
│ pressure             ┆ Pressure, pressure         ┆ 2            ┆ 5                        │
│ temperature          ┆ Temperature, temperature   ┆ 2            ┆ 5                        │
│ timestamp            ┆ timestamp                  ┆ 1            ┆ 5                        │
└──────────────────────┴────────────────────────────┴──────────────┴──────────────────────────┘

### Observations

Hétérogénéités à harmoniser en `staging/` :

- **Casse non uniforme** : `temperature`/`Temperature`, `pressure`/`Pressure`
  (et `elapsed_time`/`Elapsed_time`) selon les fichiers → **normaliser en minuscules**.
- **`elapsed_time` optionnel** : présent dans LineA et LineB seulement, absent de
  LineC/D/E → prévoir une colonne **facultative** (valeur manquante = **`null`** natif Polars, persistée en `NULL` Parquet).
- `timestamp` et `label` sont cohérents (nom + casse) sur les 5 lignes.

## 4. Types de données

In [5]:
explore.dtypes_table(paths)

shape: (5, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ colonne        ┆ LineA_Stable_1 ┆ LineB_Flux.csv ┆ LineC_Turbule ┆ LineD_SpikeCo ┆ LineE_SmoothR │
│ (normalisée)   ┆ 0K.csv         ┆ ---            ┆ nt.csv        ┆ ntrol.csv     ┆ un.csv        │
│ ---            ┆ ---            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ str            ┆                ┆ str           ┆ str           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ elapsed_time   ┆ Float64        ┆ Float64        ┆ null          ┆ null          ┆ null          │
│ label          ┆ Int64          ┆ Int64          ┆ Int64         ┆ Int64         ┆ Int64         │
│ pressure       ┆ Float64        ┆ Float64        ┆ Float64       ┆ Float64       ┆ Float64       │
│ temperature    ┆ Float64        ┆ Float64        ┆ Float64       ┆ Float64       ┆ Float64       │
│ timestamp      ┆ String         ┆ String         ┆ String        ┆ String        ┆ String        │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

## 5. `label` — valeurs & distribution

In [6]:
explore.label_distribution(paths)

shape: (5, 5)
┌────────────────────────┬───────────┬────────┬───────────┬─────────────┐
│ fichier                ┆ valeurs   ┆ lignes ┆ anomalies ┆ %_anomalies │
│ ---                    ┆ ---       ┆ ---    ┆ ---       ┆ ---         │
│ str                    ┆ list[i64] ┆ i64    ┆ i64       ┆ f64         │
╞════════════════════════╪═══════════╪════════╪═══════════╪═════════════╡
│ LineA_Stable_10K.csv   ┆ [0, 1]    ┆ 10000  ┆ 18        ┆ 0.18        │
│ LineB_Flux.csv         ┆ [0, 1]    ┆ 5000   ┆ 50        ┆ 1.0         │
│ LineC_Turbulent.csv    ┆ [0, 1]    ┆ 5000   ┆ 200       ┆ 4.0         │
│ LineD_SpikeControl.csv ┆ [0, 1]    ┆ 5000   ┆ 15        ┆ 0.3         │
│ LineE_SmoothRun.csv    ┆ [0, 1]    ┆ 5000   ┆ 25        ┆ 0.5         │
└────────────────────────┴───────────┴────────┴───────────┴─────────────┘

### Observations — `label`

- `label` vaut **{0, 1}** partout : `0` = fonctionnement nominal, `1` = anomalie.
  C'est la cible du futur projet de maintenance prédictive.

### Écart doc ↔ données (à tracer pour C20)

Le « % of Anomalies » annoncé par la description du jeu de données **ne correspond
pas toujours** au comptage réel ci-dessus :

| ligne | annoncé (doc) | mesuré (données) |
|---|---|---|
| LineE | **0 %** | **0,5 %** (25 anomalies) |
| LineB | « < 1 % » | **1,00 %** (pile) |

→ **La donnée fait foi.** À consigner comme avertissement qualité dans la fiche
OpenMetadata : ne pas présumer LineE « sans anomalie ».

## 6. Couverture temporelle & partitionnement

Période, cadence et continuité par fichier — c'est ce qui détermine les partitions
`year=YYYY/month=MM/` et l'identifiant `lineX` du chemin de dépôt en `raw/`.

In [7]:
explore.coverage(paths)

shape: (5, 10)
┌───────────┬───────┬───────────┬───────────┬───────┬─────────┬─────────┬──────┬───────┬───────────┐
│ fichier   ┆ ligne ┆ debut     ┆ fin       ┆ n     ┆ cadence ┆ continu ┆ year ┆ month ┆ mois_uniq │
│ ---       ┆ ---   ┆ ---       ┆ ---       ┆ ---   ┆ ---     ┆ ---     ┆ ---  ┆ ---   ┆ ue        │
│ str       ┆ str   ┆ datetime[ ┆ datetime[ ┆ i64   ┆ str     ┆ bool    ┆ i64  ┆ str   ┆ ---       │
│           ┆       ┆ μs]       ┆ μs]       ┆       ┆         ┆         ┆      ┆       ┆ bool      │
╞═══════════╪═══════╪═══════════╪═══════════╪═══════╪═════════╪═════════╪══════╪═══════╪═══════════╡
│ LineA_Sta ┆ lineA ┆ 2025-05-0 ┆ 2025-05-0 ┆ 10000 ┆ 0:01:00 ┆ true    ┆ 2025 ┆ 05    ┆ true      │
│ ble_10K.c ┆       ┆ 1         ┆ 7         ┆       ┆         ┆         ┆      ┆       ┆           │
│ sv        ┆       ┆ 00:00:00  ┆ 22:39:00  ┆       ┆         ┆         ┆      ┆       ┆           │
│ LineB_Flu ┆ lineB ┆ 2025-04-0 ┆ 2025-04-0 ┆ 5000  ┆ 0:01:00 ┆ true    ┆ 2025 ┆ 04    ┆ true      │
│ x.csv     ┆       ┆ 1         ┆ 4         ┆       ┆         ┆         ┆      ┆       ┆           │
│           ┆       ┆ 00:00:00  ┆ 11:19:00  ┆       ┆         ┆         ┆      ┆       ┆           │
│ LineC_Tur ┆ lineC ┆ 2025-03-0 ┆ 2025-03-0 ┆ 5000  ┆ 0:01:00 ┆ true    ┆ 2025 ┆ 03    ┆ true      │
│ bulent.cs ┆       ┆ 1         ┆ 4         ┆       ┆         ┆         ┆      ┆       ┆           │
│ v         ┆       ┆ 00:00:00  ┆ 11:19:00  ┆       ┆         ┆         ┆      ┆       ┆           │
│ LineD_Spi ┆ lineD ┆ 2025-02-0 ┆ 2025-02-0 ┆ 5000  ┆ 0:01:00 ┆ true    ┆ 2025 ┆ 02    ┆ true      │
│ keControl ┆       ┆ 1         ┆ 4         ┆       ┆         ┆         ┆      ┆       ┆           │
│ .csv      ┆       ┆ 00:00:00  ┆ 11:19:00  ┆       ┆         ┆         ┆      ┆       ┆           │
│ LineE_Smo ┆ lineE ┆ 2025-01-0 ┆ 2025-01-0 ┆ 5000  ┆ 0:01:00 ┆ true    ┆ 2025 ┆ 01    ┆ true      │
│ othRun.cs ┆       ┆ 1         ┆ 4         ┆       ┆         ┆         ┆      ┆       ┆           │
│ v         ┆       ┆ 00:00:00  ┆ 11:19:00  ┆       ┆         ┆         ┆      ┆       ┆           │
└───────────┴───────┴───────────┴───────────┴───────┴─────────┴─────────┴──────┴───────┴───────────┘

### Observations — couverture

- **Échantillonnage régulier : 1 relevé/minute, continu** (ni trou ni doublon).
- **Un fichier = un seul mois** → une seule partition par ligne :

| ligne | chemin `raw/production_lines/…` |
|---|---|
| lineE | `lineE/year=2025/month=01/` |
| lineD | `lineD/year=2025/month=02/` |
| lineC | `lineC/year=2025/month=03/` |
| lineB | `lineB/year=2025/month=04/` |
| lineA | `lineA/year=2025/month=05/` |

## 7. Format observé (constats)

- **CSV** : séparateur `,`, en-tête présent (1 ligne), 1 ligne = 1 relevé.
- **`timestamp`** : format `YYYY-MM-DD HH:MM:SS` (espace, **non ISO-T**), **sans fuseau** ; cadence 1 min.
- **Unités** (d'après `data/How_to_Use.pdf`) : `temperature` en **°C**, `pressure` en **bar** ;
  `elapsed_time` = **temps de fonctionnement machine**, **unité arbitraire** (description du jeu de données).

→ Le **schéma cible**, les **paramètres d'import** et les **règles (contrat)** sont consignés dans
**[docs/architecture.md](../docs/architecture.md)** (§5–§6 et §12) — source de référence pour les DAGs.

## Conclusion

L'exploration confirme les hétérogénéités annoncées et en quantifie d'autres :

- **Casse des colonnes** non uniforme (et parfois incohérente au sein d'un même fichier) ;
  `elapsed_time` présent uniquement sur LineA et LineB.
- **Volumétrie** : LineA = 10 000 lignes (2× les autres), **1 relevé/minute, continu** ;
  un **mois distinct par ligne** (janvier→mai 2025).
- **`label`** binaire `{0,1}`, fortement **déséquilibré** (~1 %), avec un **écart doc↔données**
  sur LineE (annoncé 0 %, mesuré 0,5 %).
- **Unités** : `temperature` en °C, `pressure` en bar ; `elapsed_time` = temps de
  fonctionnement machine (unité arbitraire).

→ Les **décisions d'architecture** et les **règles techniques d'import** qui en découlent sont
consignées dans le dossier **[docs/architecture.md](../docs/architecture.md)** (livrable C18),
source de référence pour les DAGs d'ingestion et d'harmonisation.